name: Roberta_Adapter
channels:
  - pytorch
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - transformers
  - pandas
  - scikit-learn
  - pip
  - pip:
    - datasets
    - transformers[torch]